@startuml Register
start
#Beige:Public Timeline;
#APPLICATION:Register;
repeat
    #Beige:Register Page;
        if (Login with GitHub) then (yes)
        #APPLICATION:GitHub;
        #Beige:GitHub Authentication Page;
        #Beige:GitHub Login Page;
        #Beige:GitHub Confirmation Page;
        break
    endif
    -> No;
    #Beige:Register User;
    note right: Email, Password;
    #APPLICATION:Register;
repeat while (Successful) is (No) not (yes)
    #Beige: Register Confirmation Page;
    #APPLICATION:Confirm Account;
    #Beige:Email Confirmed Page;
    #APPLICATION:Public Timeline;
stop
@enduml