@startuml UnauthenticatedUserActivities
start
#beige:Public timeline;
#APPLICATION:{Username};
#beige:{Username}'s timeline;
#APPLICATION:Next page;
#beige:{Username}'s timeline;
#APPLICATION:Public timeline;
#Beige:Public timeline;
stop
@enduml
